<?php
$labels['mh_title'] = 'Podświetlenie wiadomości';
$labels['mh_matches'] = 'dopasowania';
$labels['mh_color'] = 'kolor';
$labels['mh_delete'] = 'skasuj';
$labels['mh_delete_description'] = 'Skasuj tą linię';
$labels['mh_add'] = 'dodaj wiersz';
$labels['mh_add_description'] = 'Dodaj dodatkowy wiersz pod spodem';
$labels['deleteconfirm'] = 'Czy chcesz skasować tą regułę?';
// to nie powinno się nigdy wydażyć, ale dodane mimo wszystko
$labels['headererror'] = 'Błąd w regule wiadomości';
$labels['inputempty'] = 'Jedno lub więcej dopasowań jest puste';
$labels['invalidcolor'] = 'Nieprawidłowy kolor';
?>
